# Generated by Django 6.1.1 on 2026-09-26 14:38

import cmnsd.models.mixins.TokenMixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=cmnsd.models.mixins.TokenMixin.generate_public_id, editable=False, help_text='Short unique ID for public URL / API use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='c', max_length=1)),
                ('slug', models.SlugField(help_text='Identifier in URL', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Page title', max_length=255)),
                ('body', models.TextField(blank=True, help_text='Markdown source, rendered via the |markdown filter')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
    ]
